name: check

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Static Analysis
        uses: pre-commit/action@v3.0.0
      - name: Dummy secrets file
        run: |
          tee -a .openchallenges > /dev/null <<EOT
          MARIADB_PASSWORD=dummy
          MARIADB_ROOT_PASSWORD=dummy
          GIT_HOST_KEY=DUMMY_GIT_HOST_KEY
          GIT_PRIVATE_KEY=-----BEGIN OPENSSH PRIVATE KEY-----\nDUMMY_GIT_PRIVATE_KEY\n-----END OPENSSH PRIVATE KEY-----
          AWS_LOADER_S3_ACCESS_KEY_ID=DUMMY_S3_ACCESS_KEY
          AWS_LOADER_S3_SECRET_ACCESS_KEY=DUMMY_S3_SECRET_KEY
          SECURITY_KEY=00000
          EOT
      - name: cdk --context env=dev synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          actions_comment: false
          debug_log: true
          cdk_args: '--output ./cdk.out'
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run unit tests
        run: python -m pytest tests/ -s -v
