name: check

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Static Analysis
        uses: pre-commit/action@v3.0.0
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v3
        with:
          cdk_subcommand: 'synth'
          actions_comment: false
          debug_log: true
          cdk_args: '--output ./cdk.out'
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run unit tests
        run: python -m pytest tests/ -s -v
