name: deploy-dev

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches:
      - dev

jobs:
  aws-deploy:
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::221082174873:role/sagebase-github-oidc-openchallenges-deploy"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
      environment: "dev"
      secrets-location: "ssm"
